version: "3.4"
services:
    vite-react-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vite-react-app
        ports:
            - "8080:5173"
        volumes:
            - "./src:/app/src"
        environment:
            CHOKIDAR_USEPOLLING: "true"
        tty: true
        